create table if not exists public.users (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_id text not null,
  email text,
  display_name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_id)
);

create table if not exists public.votes (
  user_id bigint not null references public.users(id) on delete cascade,
  game_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, game_id)
);

create index if not exists votes_game_id_idx on public.votes(game_id);
create index if not exists votes_created_at_idx on public.votes(created_at desc);
